//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMY.StickyNote.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMY.StickyNote.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///	[
        ///		&quot;用户&quot;, 
        ///		&quot;微软雅黑&quot;, &quot;16.0&quot;, &quot;0&quot;
        ///	],
        ///	[
        ///		&quot;默认&quot;, 
        ///		&quot;微软雅黑&quot;, &quot;16.0&quot;, &quot;0&quot;
        ///	],
        ///	[
        ///		&quot;常规&quot;, 
        ///		&quot;Segoe UI&quot;, &quot;13.0&quot;, &quot;0&quot;
        ///	],
        ///	[
        ///		&quot;手写&quot;, 
        ///		&quot;Segoe Print&quot;, &quot;13.0&quot;, &quot;0&quot;
        ///	],
        ///	[
        ///		&quot;Consolas&quot;, 
        ///		&quot;Consolas&quot;, &quot;13&quot;, &quot;0&quot;
        ///	],
        ///	[
        ///		&quot;小号&quot;, 
        ///		&quot;Segoe UI&quot;, &quot;13&quot;, &quot;0&quot;
        ///	],
        ///	[
        ///		&quot;大号&quot;, 
        ///		&quot;Segoe UI&quot;, &quot;12.0&quot;, &quot;0&quot;
        ///	],
        ///	[
        ///		&quot;Semibold&quot;, 
        ///		&quot;Segoe UI Semibold&quot;, &quot;13&quot;, &quot;0&quot;
        ///	]
        ///] 的本地化字符串。
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///	[
        ///		&quot;用户&quot;, 
        ///		&quot;#FFFFFF&quot;, &quot;#FFAEB9&quot;, &quot;#FFAEB9&quot;
        ///	], 
        ///	[
        ///		&quot;默认&quot;, 
        ///		&quot;#FFFFFF&quot;, &quot;#FFAEB9&quot;, &quot;#FFAEB9&quot;
        ///	], 
        ///	[
        ///		&quot;蓝色&quot;, 
        ///		&quot;#FFFFFF&quot;, &quot;#5CACEE&quot;, &quot;#5CACEE&quot;
        ///	], 
        ///	[
        ///		&quot;绿色&quot;, 
        ///		&quot;#FFFFFF&quot;, &quot;#7CCD7C&quot;, &quot;#7CCD7C&quot;
        ///	],  
        ///	[
        ///		&quot;紫色&quot;, 
        ///		&quot;#FFFFFF&quot;, &quot;#7A378B&quot;, &quot;#7A378B&quot;
        ///	], 
        ///	[
        ///		&quot;黄色&quot;, 
        ///		&quot;#FFFFFF&quot;, &quot;#EEE685&quot;, &quot;#EEE685&quot;
        ///	]
        ///] 的本地化字符串。
        /// </summary>
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;城市代码&quot;: [
        ///        {
        ///            &quot;省&quot;: &quot;北京&quot;,
        ///            &quot;市&quot;: [
        ///                {
        ///                    &quot;市名&quot;: &quot;北京&quot;,
        ///                    &quot;编码&quot;: &quot;101010100&quot;
        ///                },
        ///                {
        ///                    &quot;市名&quot;: &quot;朝阳&quot;,
        ///                    &quot;编码&quot;: &quot;101010300&quot;
        ///                },
        ///                {
        ///                    &quot;市名&quot;: &quot;顺义&quot;,
        ///                    &quot;编码&quot;: &quot;101010400&quot;
        ///                },
        ///                {
        ///                    &quot;市名&quot;: &quot;怀柔&quot;,
        ///                    &quot;编码&quot;: &quot;101010500&quot;
        ///                [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WeatherCode {
            get {
                return ResourceManager.GetString("WeatherCode", resourceCulture);
            }
        }
    }
}
